name: CI Pipeline

# Quando executar: a cada push ou pull request
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'       # Ignora mudanças apenas no README
      - 'docs/**'         # Ignora qualquer arquivo dentro da pasta 'docs'
      - 'LICENSE'         # Ignora o arquivo de licença
      - 'CONTRIBUTING.md' # Ignora o guia de contribuição
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'       # Ignora mudanças apenas no README
      - 'docs/**'         # Ignora qualquer arquivo dentro da pasta 'docs'
      - 'LICENSE'         # Ignora o arquivo de licença
      - 'CONTRIBUTING.md' # Ignora o guia de contribuição

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            # Fazer checkout do código
            - name: Fazer checkout do código
              uses: actions/checkout@v4

            # Configurar Python
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.12.2'
            
            - name: Instalar dependências
              run: pip install -r requirements.txt

            - name: Verificar formatação com Black
              run: black --check .

            - name: Verificar linting com Flake8
              run: flake8 .

            - name: Executar testes com pytest
              run: pytest